---
  version: '3.7'

  secrets:
    tomcat_ssl_crt:
      file: ./docker/certificates/tomcat-wildcard.crt
    tomcat_ssl_key:
      file: ./docker/certificates/tomcat-wildcard.key

  services:
    aqcu-tss-report:
      build: .
      image: aqcu-tss-report
      ports:
        - "7501:7501"
      volumes: 
        - ./docker/certificates/import_certs:/certificates:ro
      secrets:
        - source: tomcat_ssl_crt
          target: /home/spring/tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /home/spring/tomcat-wildcard-ssl.key
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env

    aqcu-tss-report-local-dev:
      build: .
      image: aqcu-tss-report
      network_mode: "host"
      ports:
        - "7501:7501"
      volumes: 
        - ./docker/certificates/import_certs:/certificates:ro
      secrets: 
        - source: tomcat_ssl_crt
          target: /home/spring/tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /home/spring/tomcat-wildcard-ssl.key
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env
        
    aqcu-tss-report-debug:
      build: .
      image: aqcu-tss-report
      network_mode: "host"
      volumes: 
        - ./docker/certificates/import_certs:/certificates:ro
      ports:
        - "7501:7501"
        - "8000:8000"
      environment:
        - JAVA_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n"
      env_file:
        - ./docker/config.env
        - ./docker/secrets.env
